"""add_transaction_models

Revision ID: d949eddcd13c
Revises: 4bf1a0c6dd85
Create Date: 2026-01-25 15:28:35.086893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd949eddcd13c'
down_revision: Union[str, None] = '4bf1a0c6dd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_cost_basis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('netuid', sa.BigInteger(), nullable=False),
    sa.Column('total_staked_tao', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('total_unstaked_tao', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('net_invested_tao', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('weighted_avg_entry_price', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('realized_pnl_tao', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('total_fees_tao', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('stake_count', sa.BigInteger(), nullable=False),
    sa.Column('unstake_count', sa.BigInteger(), nullable=False),
    sa.Column('first_stake_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_basis_wallet_netuid', 'position_cost_basis', ['wallet_address', 'netuid'], unique=True)
    op.create_table('stake_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('extrinsic_id', sa.String(length=32), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('tx_type', sa.String(length=32), nullable=False),
    sa.Column('call_name', sa.String(length=64), nullable=False),
    sa.Column('netuid', sa.BigInteger(), nullable=False),
    sa.Column('hotkey', sa.String(length=64), nullable=True),
    sa.Column('amount_tao', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=9), nullable=True),
    sa.Column('execution_price', sa.Numeric(precision=20, scale=9), nullable=True),
    sa.Column('fee_rao', sa.BigInteger(), nullable=False),
    sa.Column('fee_tao', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extrinsic_id')
    )
    op.create_index(op.f('ix_stake_transactions_netuid'), 'stake_transactions', ['netuid'], unique=False)
    op.create_index(op.f('ix_stake_transactions_timestamp'), 'stake_transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_stake_transactions_wallet_address'), 'stake_transactions', ['wallet_address'], unique=False)
    op.create_index('ix_stake_tx_timestamp', 'stake_transactions', ['timestamp'], unique=False)
    op.create_index('ix_stake_tx_wallet_netuid', 'stake_transactions', ['wallet_address', 'netuid'], unique=False)
    op.create_index('ix_stake_tx_wallet_type', 'stake_transactions', ['wallet_address', 'tx_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stake_tx_wallet_type', table_name='stake_transactions')
    op.drop_index('ix_stake_tx_wallet_netuid', table_name='stake_transactions')
    op.drop_index('ix_stake_tx_timestamp', table_name='stake_transactions')
    op.drop_index(op.f('ix_stake_transactions_wallet_address'), table_name='stake_transactions')
    op.drop_index(op.f('ix_stake_transactions_timestamp'), table_name='stake_transactions')
    op.drop_index(op.f('ix_stake_transactions_netuid'), table_name='stake_transactions')
    op.drop_table('stake_transactions')
    op.drop_index('ix_cost_basis_wallet_netuid', table_name='position_cost_basis')
    op.drop_table('position_cost_basis')
    # ### end Alembic commands ###
