"""add_alpha_amount_and_usd_value_to_transactions

Revision ID: dbe03dba9980
Revises: f24817dfe0c8
Create Date: 2026-01-25 17:43:16.516749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe03dba9980'
down_revision: Union[str, None] = 'f24817dfe0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stake_transactions', sa.Column('alpha_amount', sa.Numeric(precision=20, scale=9), nullable=True))
    op.add_column('stake_transactions', sa.Column('usd_value', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stake_transactions', 'usd_value')
    op.drop_column('stake_transactions', 'alpha_amount')
    # ### end Alembic commands ###
