"""add_subnet_name_to_position

Revision ID: f24817dfe0c8
Revises: d949eddcd13c
Create Date: 2026-01-25 15:39:31.293434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24817dfe0c8'
down_revision: Union[str, None] = 'd949eddcd13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('subnet_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'subnet_name')
    # ### end Alembic commands ###
